[project]
name = "sfloutage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lisaHerradi", email = "lisaherradi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=6.0.0",
    "onnx>=1.23.1",
    "onnxruntime-gpu>=1.30.0",
    "opencv-python>=5.0.0.93",
    "pyyaml>=6.0.3",
    "tqdm>=4.70.1",
    "ultralytics>=8.4.172",
]

[project.scripts]
sfloutage = "sfloutage:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
license = "AGPL-3.0-or-later"
